name: Daily HustleBot

on:
  schedule:
    - cron: "0 0,8,16 * * *" # 00:00, 08:00, 16:00
    - cron: "36 1,9,17 * * *" # 01:36, 09:36, 17:36
    - cron: "12 3,11,19 * * *" # 03:12, 11:12, 19:12
    - cron: "48 4,12,20 * * *" # 04:48, 12:48, 20:48
    - cron: "24 6,14,22 * * *" # 06:24, 14:24, 22:24
  workflow_dispatch: # Allows you to click "Run Now" manually for testing

jobs:
  hunt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python automate.py --once
